### ISSUE TITLE
[日报模板]: 预览显示不全

### ISSUE THREAD

**Issue by Wangpingyue** [imc-ux/ReportsMS#31]
### Describe the problem

预览之后，样式显示不全

### Describe the proposed solution

请修改，显示全内容

### Screenshot

![2023-12-28_150716](https://github.com/imc-ux/ReportsMS/assets/144862216/a7bb09bc-8158-47eb-9e24-26d9c9e59eb3)

### Importance

nice to have

**Comment by foster7n15** [comment]
与issues/14重复.

**Comment by ythyhvh** [comment]
#14 重复 关闭
