### ISSUE TITLE
[页面名称]: 模板以及消息管理需要加权限

### ISSUE THREAD

**Issue by liujinhai8410** [imc-ux/ReportsMS#43]
### Describe the problem

模板以及模板需要加权限

### Describe the proposed solution

模板以及模板需要加权限

### Importance

nice to have

**Comment by ythyhvh** [comment]
没有管理权限的  不能选择用户下拉列表  只能查看自己名下记录       @liujinhai8410

**Comment by ythyhvh** [comment]
其他按钮用户权限  按照其他页面标准进行
